import streamlit as st
import streamlit.components.v1 as components
import requests, pickle, numpy as np, plotly.graph_objects as go
import pandas as pd
from PIL import Image
from io import BytesIO
from fpdf import FPDF
import datetime, urllib3, urllib.parse, base64, json, re, os, io, urllib.request

from mappings import soil_properties, season_rainfall
from weather import get_live_weather

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

st.set_page_config(page_title="Assam Crop Advisor", page_icon="🌾",
                   layout="wide", initial_sidebar_state="expanded")

# ═══════════════════════════════════════════════════════════════════════════════
# LANGUAGE SYSTEM
# ═══════════════════════════════════════════════════════════════════════════════
UI_TEXT = {
    "en": {
        "title":"🌾 Assam Crop Advisor","subtitle":"AI-powered crop advice for Assam farmers",
        "soil_header":"Soil & Season Details","soil_type":"Soil Type","season":"Current Season",
        "district":"District / City","input_mode":"Input Mode","simple":"Simple Mode","advanced":"Advanced Mode",
        "display_opts":"Display Options","show_dash":"Environmental dashboard",
        "show_history":"Crop history comparison","num_recs":"Recommendations to show",
        "predict_btn":"Get Crop Recommendations","top_rec":"Top Recommendation",
        "why_crop":"Why this crop?","confidence":"Model confidence","top_n_recs":"All Recommendations",
        "env_analysis":"Environmental Analysis","history_title":"Recommendation History",
        "clear_history":"Clear History","export_title":"Export Report",
        "export_desc":"Download a printable PDF summary for field use.",
        "download_pdf":"Download PDF Report","input_summary":"View input summary",
        "fert_title":"Fertilizer Prescription","fert_desc":"Soil deficit vs crop requirement:",
        "fert_optimal":"Soil nutrient levels are optimal for this crop!",
        "market_title":"Market & Economics Forecast","market_price":"Market Price",
        "market_yield":"Yield / hectare","market_revenue":"Gross Revenue",
        "market_cost":"Input Cost","market_profit":"Net Profit",
        "market_note":"Based on Assam Mandi averages. Actual prices may vary.",
        "water_need":"Water need","lang_toggle":"Language","location_hdr":"Location",
        "input_mode_hdr":"Input Mode","caption":"Built for Assam farmers · v4.0\nRandom Forest ML",
        "fetching":"Fetching weather & running AI analysis…","analysis_done":"Analysis complete!",
        "model_not_found":"Model files not found! Run train_model.ipynb first.",
        "weather_error":"Weather API Error","best_fit":"Best fit for conditions in",
        "best_fit2":"based on soil, weather & season.",
        "real_photo":"Real photo","ai_matched":"AI matched","based_on":"based on soil pH",
        "live_weather":"live weather","exp_rainfall_prefix":"Expected rainfall:","exp_rainfall_suffix":"mm rainfall.",
        "Loamy / Alluvial":"Loamy / Alluvial","Sandy / Riverbank":"Sandy / Riverbank","Clay":"Clay","Red Laterite":"Red Laterite",
        "Tea Garden Soil":"Tea Garden Soil","Hill / Forest Loam":"Hill / Forest Loam","Peaty / Waterlogged":"Peaty / Waterlogged","Sandy Loam":"Sandy Loam",
        "Pre-Monsoon  (Mar – May)":"Pre-Monsoon (Mar-May)","Monsoon      (Jun – Sep)":"Monsoon (Jun-Sep)","Post-Monsoon (Oct – Nov)":"Post-Monsoon (Oct-Nov)","Winter       (Dec – Feb)":"Winter (Dec-Feb)",
        "hist_align":"Conditions align with historical Assam growing data.",
        "nitrogen":"Nitrogen (N)","phosphorus":"Phosphorus (P)","potassium":"Potassium (K)",
        "npk_title":"Soil NPK Balance","npk_desc":"Soil NPK balance represents the levels of Nitrogen (N), Phosphorus (P), and Potassium (K) in your soil. These are the three primary nutrients essential for healthy crop growth and high yields.",
        "soil_ph":"Soil pH","rainfall_mm":"Rainfall (mm)","temperature":"Temperature (C)",
        "humidity":"Humidity (%)","district_lbl":"District","value":"Value",
        "pdf_report":"AI Crop Recommendation Report","pdf_date":"Date Generated",
        "pdf_location":"Analyzed Location","pdf_top_crop":"Top Recommended Crop",
        "pdf_env":"Environmental & Soil Data","pdf_footer":"Generated by Assam Crop Recommendation System.",
        "pdf_fert":"Fertilizer Prescription","pdf_market":"Market & Economics Forecast",
        "add_urea":"Add Urea","add_dap":"Add DAP","add_mop":"Add MOP",
        "kg_per_ha":"kg/hectare","no_deficit":"No amendment needed","per_ha":"per hectare",
        "cam_header":"Identify Crop from Photo","cam_take":"Take a photo",
        "cam_upload":"Or upload image","cam_detecting":"Identifying crop…",
        "cam_detected":"Detected","cam_no_disease":"No disease found.",
        "cam_error":"Could not identify crop","cam_pre_filled":"Camera detected",
        "listen_btn":"Listen to recommendation",
        "presc_header":"Prescription (per hectare)",
        "urea_label":"Urea (46% N)","dap_label":"DAP (18N+46P)","mop_label":"MOP (60% K)",
        "cam_toggle":"Use Camera Input",
    },
    "as": {
        "title":"🌾 অসম শস্য পৰামৰ্শ প্ৰণালী","subtitle":"অসম কৃষকৰ বাবে AI-চালিত শস্য পৰামৰ্শ",
        "soil_header":"মাটি আৰু ঋতুৰ বিৱৰণ","soil_type":"মাটিৰ প্ৰকাৰ","season":"বৰ্তমান ঋতু",
        "district":"জিলা / চহৰ","input_mode":"ইনপুট মোড","simple":"সহজ মোড","advanced":"উন্নত মোড",
        "display_opts":"প্ৰদৰ্শন বিকল্প","show_dash":"পৰিৱেশ ড্যাশব'ৰ্ড",
        "show_history":"শস্যৰ ইতিহাস তুলনা","num_recs":"পৰামৰ্শৰ সংখ্যা",
        "predict_btn":"শস্যৰ পৰামৰ্শ লওক","top_rec":"শীৰ্ষ পৰামৰ্শ",
        "why_crop":"এই শস্য কিয়?","confidence":"মডেলৰ আত্মবিশ্বাস","top_n_recs":"সকলো পৰামৰ্শ",
        "env_analysis":"পৰিৱেশ বিশ্লেষণ","history_title":"পৰামৰ্শৰ ইতিহাস",
        "clear_history":"ইতিহাস মচক","export_title":"প্ৰতিবেদন ৰপ্তানি কৰক",
        "export_desc":"ক্ষেত্ৰ ব্যৱহাৰৰ বাবে PDF সাৰাংশ ডাউনলোড কৰক।",
        "download_pdf":"PDF প্ৰতিবেদন ডাউনলোড কৰক","input_summary":"ইনপুট সাৰাংশ চাওক",
        "fert_title":"সাৰ প্ৰেচক্ৰিপচন","fert_desc":"মাটিৰ পুষ্টি ঘাটি বনাম শস্যৰ প্ৰয়োজন:",
        "fert_optimal":"এই শস্যৰ বাবে মাটিৰ পুষ্টি স্তৰ সৰ্বোত্তম!",
        "market_title":"বজাৰ আৰু অৰ্থনীতি পূৰ্বানুমান","market_price":"বজাৰ মূল্য",
        "market_yield":"উৎপাদন / হেক্টৰ","market_revenue":"মুঠ ৰাজহ",
        "market_cost":"ইনপুট খৰচ","market_profit":"নিট লাভ",
        "market_note":"অসম মণ্ডিৰ গড়ৰ ওপৰত ভিত্তি কৰি।",
        "water_need":"পানীৰ প্ৰয়োজন","lang_toggle":"ভাষা","location_hdr":"স্থান",
        "input_mode_hdr":"ইনপুট মোড","caption":"অসমৰ কৃষকৰ বাবে · v4.0\nRandom Forest ML",
        "fetching":"বতৰৰ ডেটা আনি AI বিশ্লেষণ চলাইছে…","analysis_done":"বিশ্লেষণ সম্পূৰ্ণ!",
        "model_not_found":"মডেল ফাইল পোৱা নগ'ল!",
        "weather_error":"বতৰ API ত্ৰুটি","best_fit":"ইয়াত সৰ্বোত্তম",
        "best_fit2":"মাটি, বতৰ আৰু ঋতুৰ ওপৰত ভিত্তি কৰি।",
        "real_photo":"প্ৰকৃত ফটো","ai_matched":"AI এ মিলাইছে","based_on":"মাটিৰ pH",
        "live_weather":"লাইভ বতৰ","exp_rainfall_prefix":"প্ৰত্যাশিত বৃষ্টিপাত:","exp_rainfall_suffix":"mm বৃষ্টিপাত।",
        "Loamy / Alluvial":"দোমোজা / পলসুৱা মাটি","Sandy / Riverbank":"বালিয়া / নদীৰ পাৰৰ মাটি","Clay":"বোকা / আলতীয়া মাটি","Red Laterite":"ৰঙা লেটাৰাইট মাটি",
        "Tea Garden Soil":"চাহ বাগিচাৰ মাটি","Hill / Forest Loam":"পাহাৰীয়া / হাবিৰ মাটি","Peaty / Waterlogged":"পিটি / জলমগ্ন মাটি","Sandy Loam":"বালিয়া পলসুৱা মাটি",
        "Pre-Monsoon  (Mar – May)":"প্ৰাক-মৌচমী (মাৰ্চ – মে')","Monsoon      (Jun – Sep)":"মৌচমী (জুন – ছেপ্টেম্বৰ)","Post-Monsoon (Oct – Nov)":"উত্তৰ-মৌচমী (অক্টোবৰ – নৱেম্বৰ)","Winter       (Dec – Feb)":"শীতকাল (ডিচেম্বৰ – ফেব্ৰুৱাৰী)",
        "hist_align":"এই অৱস্থাসমূহ অসমত ঐতিহাসিক ডেটাৰ সৈতে মিলে।",
        "nitrogen":"নাইট্ৰজেন (N)","phosphorus":"ফছফৰাছ (P)","potassium":"পটাছিয়াম (K)",
        "npk_title":"মাটিৰ NPK সন্তুলন","npk_desc":"মাটিৰ NPK সন্তুলনে আপোনাৰ মাটিত থকা নাইট্ৰজেন (N), ফছফৰাছ (P) আৰু পটাছিয়ামৰ (K) মাত্ৰাক সূচায়। এই তিনিটা মুখ্য পুষ্টি উপাদান শস্যৰ স্বাস্থ্যকৰ বৃদ্ধি আৰু অধিক উৎপাদনৰ বাবে অপৰিহাৰ্য।",
        "soil_ph":"মাটিৰ pH","rainfall_mm":"বৃষ্টিপাত (mm)","temperature":"তাপমাত্ৰা (C)",
        "humidity":"আৰ্দ্ৰতা (%)","district_lbl":"জিলা","value":"মান",
        "pdf_report":"AI শস্য পৰামৰ্শ প্ৰতিবেদন","pdf_date":"উৎপাদনৰ তাৰিখ",
        "pdf_location":"বিশ্লেষণ কৰা স্থান","pdf_top_crop":"শীৰ্ষ পৰামৰ্শ কৰা শস্য",
        "pdf_env":"পৰিৱেশ আৰু মাটিৰ ডেটা","pdf_footer":"অসম শস্য পৰামৰ্শ প্ৰণালীৰ দ্বাৰা উৎপন্ন।",
        "pdf_fert":"সাৰ প্ৰেচক্ৰিপচন","pdf_market":"বজাৰ আৰু অৰ্থনীতি পূৰ্বানুমান",
        "add_urea":"ইউৰিয়া যোগ কৰক","add_dap":"DAP যোগ কৰক","add_mop":"MOP যোগ কৰক",
        "kg_per_ha":"কেজি/হেক্টৰ","no_deficit":"সংশোধনৰ প্ৰয়োজন নাই","per_ha":"প্ৰতি হেক্টৰ",
        "cam_header":"ফটোৰ পৰা শস্য চিনাক্ত কৰক","cam_take":"ফটো তোলক",
        "cam_upload":"বা ছবি আপলোড কৰক","cam_detecting":"শস্য চিনাক্ত কৰা হৈছে…",
        "cam_detected":"চিনাক্ত হৈছে","cam_no_disease":"কোনো ৰোগ পোৱা নগ'ল।",
        "cam_error":"শস্য চিনাক্ত কৰিব পৰা নগ'ল","cam_pre_filled":"কেমেৰাই চিনাক্ত কৰিছে",
        "listen_btn":"পৰামৰ্শ শুনক",
        "presc_header":"প্ৰেচক্ৰিপচন (প্ৰতি হেক্টৰ)",
        "urea_label":"ইউৰিয়া (46% N)","dap_label":"DAP (18N+46P)","mop_label":"MOP (60% K)",
        "cam_toggle":"কেমেৰা ব্যৱহাৰ কৰক",
    }
}

def T(key):
    lang = st.session_state.get("lang","en")
    return UI_TEXT.get(lang, UI_TEXT["en"]).get(key, key)


# ═══════════════════════════════════════════════════════════════════════════════
# GEMINI CAMERA RECOGNITION
# ═══════════════════════════════════════════════════════════════════════════════
_ALL_CROP_KEYS = [
    "rice","wheat","maize","jute","assam_tea","mustard","sugarcane","cotton",
    "banana","mango","chickpea","lentil","papaya","coconut","pomegranate",
    "grapes","watermelon","muskmelon","orange","apple","mungbean","mothbeans",
    "pigeonpeas","kidneybeans","blackgram","coffee","joha_rice","joha_rice72",
    "bao_rice","bora_rice","chokuwa_rice","komal_saul","xaaj_rice","apong_rice",
    "bhut_jolokia","kaji_nemu","ou_tenga","thekera","amlokhi","bogori","leteku",
    "jalpai","areca_nut","betel_leaf","kola_banana","lai_xaak","kosu",
    "dhekia_xaak","manimuni","local_brinjal","local_pumpkin","local_beans","bamboo_shoot",
]
_CROP_KEY_ALIASES = {
    "glutinous_rice":"bora_rice","sticky_rice":"bora_rice","deepwater_rice":"bao_rice",
    "boro_rice":"bao_rice","green_chili":"bhut_jolokia","ghost_pepper":"bhut_jolokia",
    "chili":"bhut_jolokia","pepper":"bhut_jolokia","lemon":"kaji_nemu","citrus":"kaji_nemu",
    "lichi":"leteku","litchi":"leteku","taro":"kosu","colocasia":"kosu",
    "fern":"dhekia_xaak","pennywort":"manimuni","brinjal":"local_brinjal",
    "eggplant":"local_brinjal","pumpkin":"local_pumpkin","beans":"local_beans",
    "bamboo":"bamboo_shoot","areca":"areca_nut","betel":"betel_leaf","tea":"assam_tea",
    "paddy":"rice","corn":"maize",
}

def _normalise_crop_key(raw):
    k = raw.lower().strip().replace(" ","_").replace("-","_")
    if k in _ALL_CROP_KEYS: return k
    if k in _CROP_KEY_ALIASES: return _CROP_KEY_ALIASES[k]
    for known in _ALL_CROP_KEYS:
        if known in k or k in known: return known
    return "rice"

def _resize_image(img_bytes, max_px=512, quality=80):
    pil = Image.open(io.BytesIO(img_bytes)).convert("RGB")
    pil.thumbnail((max_px,max_px), Image.LANCZOS)
    buf = io.BytesIO()
    pil.save(buf, format="JPEG", quality=quality)
    return buf.getvalue()

@st.cache_data(ttl=3600, show_spinner=False)
def identify_crop_from_image(img_bytes):
    try:
        api_key = st.secrets["GEMINI_API_KEY"]
    except Exception:
        return {"crop_key":"unknown","display_name":"Unknown","disease":None,
                "confidence":0,"notes":"GEMINI_API_KEY not set in Streamlit secrets."}
    try:
        img_bytes = _resize_image(img_bytes)
    except Exception:
        pass
    b64 = base64.b64encode(img_bytes).decode("utf-8")
    keys_str = ", ".join(_ALL_CROP_KEYS)
    prompt = (
        "You are an expert agronomist for Assam, India.\n"
        "Look at the image and identify the crop or plant.\n"
        f"Pick ONE key from: [{keys_str}]\n\n"
        "Reply ONLY with JSON, no markdown:\n"
        '{"crop_key":"rice","display_name":"Rice","disease":null,"confidence":90,"notes":"Healthy paddy field"}'
    )
    payload = {
        "contents":[{"parts":[
            {"inline_data":{"mime_type":"image/jpeg","data":b64}},
            {"text":prompt},
        ]}],
        "generationConfig":{"temperature":0.1,"maxOutputTokens":256},
    }
    for model in ["gemini-2.0-flash","gemini-1.5-flash"]:
        url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
               f"{model}:generateContent?key={api_key}")
        try:
            resp = requests.post(url, json=payload, timeout=30,
                                 headers={"Content-Type":"application/json"})
            if resp.status_code == 404: continue
            if resp.status_code != 200:
                return {"crop_key":"unknown","display_name":"Unknown","disease":None,
                        "confidence":0,"notes":f"API error {resp.status_code}"}
            raw   = (resp.json().get("candidates",[{}])[0]
                     .get("content",{}).get("parts",[{}])[0].get("text","").strip())
            clean = re.sub(r"```(?:json)?|```","",raw).strip()
            m     = re.search(r'\{.*\}', clean, re.DOTALL)
            if m: clean = m.group(0)
            result = json.loads(clean)
            result["crop_key"] = _normalise_crop_key(result.get("crop_key","rice"))
            return result
        except Exception as e:
            return {"crop_key":"unknown","display_name":"Unknown","disease":None,
                    "confidence":0,"notes":f"Error: {str(e)}"}
    return {"crop_key":"unknown","display_name":"Unknown","disease":None,
            "confidence":0,"notes":"All Gemini models unavailable."}


# ═══════════════════════════════════════════════════════════════════════════════
# TTS PLAYER
# ═══════════════════════════════════════════════════════════════════════════════
def build_tts_summary(crop_name, fert, market, lang="en", crop_key=None):
    if crop_key in CROP_FACTS:
        fact = CROP_FACTS[crop_key].get(lang, CROP_FACTS[crop_key]["en"])
        if lang == "as":
            return f"{crop_name}ৰ বিষয়ে কিছু তথ্য: {fact}"
        return f"Few facts about {crop_name}: {fact}"

    if lang == "as":
        return (f"শীৰ্ষ পৰামৰ্শিত শস্য: {crop_name}। "
                f"ইউৰিয়া {fert['urea_kg']} কেজি, DAP {fert['dap_kg']} কেজি, "
                f"MOP {fert['mop_kg']} কেজি প্ৰতি হেক্টৰত প্ৰয়োগ কৰক। "
                f"নিট লাভ {market['net_profit']:,} টকা। ROI: {market['roi_pct']} শতাংশ।")
    return (f"Top recommended crop: {crop_name}. "
            f"Apply {fert['urea_kg']} kg Urea, {fert['dap_kg']} kg DAP, "
            f"and {fert['mop_kg']} kg MOP per hectare. "
            f"Estimated net profit: Rupees {market['net_profit']:,}. "
            f"Return on investment: {market['roi_pct']} percent.")

def render_tts_player(text, lang="en"):
    lang_code = "as-IN" if lang == "as" else "en-IN"
    escaped   = text.replace("\\","\\\\").replace("'","\\'").replace('"','\\"').replace("\n"," ")
    preview   = text[:80] + "…" if len(text) > 80 else text
    components.html(f"""
<div style="display:flex;align-items:center;gap:10px;padding:.65rem 1rem;
     background:rgba(37,99,235,.08);border:1px solid rgba(37,99,235,.2);
     border-radius:12px;font-size:13px;font-family:sans-serif;margin-top:8px;">
  <button onclick="ttsPlay()" title="Play"
    style="min-width:38px;height:38px;border-radius:50%;border:2px solid #2563eb;
           background:#2563eb;color:white;cursor:pointer;font-size:16px;flex-shrink:0;">&#9654;</button>
  <button onclick="window.speechSynthesis.cancel()" title="Stop"
    style="min-width:38px;height:38px;border-radius:50%;border:2px solid #ccc;
           background:white;color:#555;cursor:pointer;font-size:16px;flex-shrink:0;">&#9632;</button>
  <span style="flex:1;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;color:#555;">{preview}</span>
</div>
<script>
(function(){{
  var TEXT='{escaped}',LANG='{lang_code}';
  function pickVoice(l){{
    var vv=window.speechSynthesis.getVoices();
    for(var v of vv){{if(v.lang===l)return v;}}
    var p=l.split('-')[0];
    for(var v of vv){{if(v.lang.startsWith(p))return v;}}
    return null;
  }}
  window.ttsPlay=function(){{
    window.speechSynthesis.cancel();
    var u=new SpeechSynthesisUtterance(TEXT);
    var v=pickVoice(LANG)||pickVoice('en-IN');
    if(v){{u.voice=v;}} u.lang=v?v.lang:'en-IN'; u.rate=0.88; u.pitch=1.0;
    window.speechSynthesis.speak(u);
  }};
  window.speechSynthesis.onvoiceschanged=function(){{window.speechSynthesis.getVoices();}};
}})();
</script>""", height=66)


# ═══════════════════════════════════════════════════════════════════════════════
# FERTILIZER ENGINE
# ═══════════════════════════════════════════════════════════════════════════════
CROP_NPK_REQUIREMENTS = {
    "rice":{"N":80,"P":40,"K":40},"wheat":{"N":120,"P":60,"K":40},
    "maize":{"N":120,"P":60,"K":60},"jute":{"N":60,"P":30,"K":30},
    "assam_tea":{"N":150,"P":30,"K":50},"mustard":{"N":80,"P":40,"K":40},
    "sugarcane":{"N":250,"P":60,"K":120},"cotton":{"N":100,"P":50,"K":50},
    "banana":{"N":200,"P":60,"K":300},"mango":{"N":100,"P":50,"K":100},
    "chickpea":{"N":20,"P":60,"K":30},"lentil":{"N":20,"P":40,"K":20},
    "papaya":{"N":200,"P":200,"K":250},"coconut":{"N":100,"P":40,"K":200},
    "pomegranate":{"N":60,"P":60,"K":60},"grapes":{"N":100,"P":60,"K":80},
    "watermelon":{"N":80,"P":40,"K":60},"muskmelon":{"N":80,"P":40,"K":60},
    "orange":{"N":100,"P":50,"K":100},"apple":{"N":70,"P":35,"K":70},
    "mungbean":{"N":20,"P":40,"K":20},"mothbeans":{"N":20,"P":40,"K":20},
    "pigeonpeas":{"N":20,"P":50,"K":20},"kidneybeans":{"N":20,"P":60,"K":30},
    "blackgram":{"N":20,"P":40,"K":20},"coffee":{"N":150,"P":50,"K":100},
    "joha_rice":{"N":60,"P":30,"K":30},"joha_rice72":{"N":60,"P":30,"K":30},
    "bao_rice":{"N":50,"P":25,"K":25},"bora_rice":{"N":70,"P":35,"K":35},
    "chokuwa_rice":{"N":55,"P":28,"K":28},"komal_saul":{"N":50,"P":25,"K":25},
    "xaaj_rice":{"N":60,"P":30,"K":30},"apong_rice":{"N":60,"P":30,"K":30},
    "bhut_jolokia":{"N":100,"P":60,"K":80},"kaji_nemu":{"N":80,"P":40,"K":60},
    "ou_tenga":{"N":60,"P":30,"K":40},"thekera":{"N":50,"P":25,"K":30},
    "amlokhi":{"N":60,"P":30,"K":50},"bogori":{"N":50,"P":25,"K":30},
    "leteku":{"N":80,"P":40,"K":60},"jalpai":{"N":60,"P":30,"K":40},
    "areca_nut":{"N":100,"P":40,"K":140},"betel_leaf":{"N":80,"P":40,"K":60},
    "kola_banana":{"N":180,"P":60,"K":280},"lai_xaak":{"N":60,"P":30,"K":30},
    "kosu":{"N":100,"P":50,"K":100},"dhekia_xaak":{"N":40,"P":20,"K":20},
    "manimuni":{"N":30,"P":15,"K":15},"local_brinjal":{"N":100,"P":50,"K":60},
    "local_pumpkin":{"N":80,"P":60,"K":80},"local_beans":{"N":20,"P":60,"K":30},
    "bamboo_shoot":{"N":60,"P":30,"K":40},
}

def calculate_fertilizer_prescription(crop_key, actual_N, actual_P, actual_K):
    req       = CROP_NPK_REQUIREMENTS.get(crop_key.lower(),{"N":80,"P":40,"K":40})
    deficit_N = max(0, req["N"]-actual_N)
    deficit_P = max(0, req["P"]-actual_P)
    deficit_K = max(0, req["K"]-actual_K)
    dap_kg    = deficit_P / 0.46
    urea_kg   = max(0, deficit_N - dap_kg*0.18) / 0.46
    mop_kg    = deficit_K / 0.60
    return {"required":req,
            "deficit_N":round(deficit_N),"deficit_P":round(deficit_P),"deficit_K":round(deficit_K),
            "urea_kg":round(urea_kg),"dap_kg":round(dap_kg),"mop_kg":round(mop_kg),
            "all_optimal":deficit_N==0 and deficit_P==0 and deficit_K==0}


# ═══════════════════════════════════════════════════════════════════════════════
# MARKET FORECASTER
# ═══════════════════════════════════════════════════════════════════════════════
MARKET_DATA = {
    "rice":{"price_per_q":2200,"yield_q_ha":25,"input_cost":25000},
    "wheat":{"price_per_q":2275,"yield_q_ha":30,"input_cost":22000},
    "maize":{"price_per_q":1850,"yield_q_ha":35,"input_cost":18000},
    "jute":{"price_per_q":5500,"yield_q_ha":20,"input_cost":20000},
    "assam_tea":{"price_per_q":15000,"yield_q_ha":18,"input_cost":80000},
    "mustard":{"price_per_q":5650,"yield_q_ha":10,"input_cost":15000},
    "sugarcane":{"price_per_q":315,"yield_q_ha":600,"input_cost":40000},
    "cotton":{"price_per_q":6600,"yield_q_ha":15,"input_cost":35000},
    "banana":{"price_per_q":1500,"yield_q_ha":200,"input_cost":45000},
    "mango":{"price_per_q":3000,"yield_q_ha":80,"input_cost":30000},
    "chickpea":{"price_per_q":5440,"yield_q_ha":12,"input_cost":18000},
    "lentil":{"price_per_q":6000,"yield_q_ha":10,"input_cost":15000},
    "papaya":{"price_per_q":800,"yield_q_ha":250,"input_cost":35000},
    "coconut":{"price_per_q":2500,"yield_q_ha":120,"input_cost":25000},
    "pomegranate":{"price_per_q":8000,"yield_q_ha":80,"input_cost":40000},
    "grapes":{"price_per_q":6000,"yield_q_ha":100,"input_cost":50000},
    "watermelon":{"price_per_q":600,"yield_q_ha":250,"input_cost":20000},
    "muskmelon":{"price_per_q":1200,"yield_q_ha":150,"input_cost":20000},
    "orange":{"price_per_q":4000,"yield_q_ha":100,"input_cost":35000},
    "apple":{"price_per_q":8000,"yield_q_ha":80,"input_cost":45000},
    "mungbean":{"price_per_q":7755,"yield_q_ha":8,"input_cost":12000},
    "mothbeans":{"price_per_q":6000,"yield_q_ha":7,"input_cost":10000},
    "pigeonpeas":{"price_per_q":7000,"yield_q_ha":10,"input_cost":12000},
    "kidneybeans":{"price_per_q":9000,"yield_q_ha":12,"input_cost":18000},
    "blackgram":{"price_per_q":7400,"yield_q_ha":8,"input_cost":12000},
    "coffee":{"price_per_q":18000,"yield_q_ha":8,"input_cost":50000},
    "joha_rice":{"price_per_q":6000,"yield_q_ha":18,"input_cost":22000},
    "joha_rice72":{"price_per_q":5500,"yield_q_ha":20,"input_cost":22000},
    "bao_rice":{"price_per_q":3500,"yield_q_ha":20,"input_cost":20000},
    "bora_rice":{"price_per_q":4500,"yield_q_ha":18,"input_cost":20000},
    "chokuwa_rice":{"price_per_q":5000,"yield_q_ha":18,"input_cost":20000},
    "komal_saul":{"price_per_q":7000,"yield_q_ha":15,"input_cost":22000},
    "xaaj_rice":{"price_per_q":4000,"yield_q_ha":20,"input_cost":20000},
    "apong_rice":{"price_per_q":4000,"yield_q_ha":20,"input_cost":20000},
    "bhut_jolokia":{"price_per_q":25000,"yield_q_ha":12,"input_cost":30000},
    "kaji_nemu":{"price_per_q":4000,"yield_q_ha":80,"input_cost":20000},
    "ou_tenga":{"price_per_q":2000,"yield_q_ha":60,"input_cost":15000},
    "thekera":{"price_per_q":3000,"yield_q_ha":40,"input_cost":15000},
    "amlokhi":{"price_per_q":3500,"yield_q_ha":60,"input_cost":20000},
    "bogori":{"price_per_q":2500,"yield_q_ha":50,"input_cost":15000},
    "leteku":{"price_per_q":5000,"yield_q_ha":50,"input_cost":20000},
    "jalpai":{"price_per_q":2000,"yield_q_ha":40,"input_cost":15000},
    "areca_nut":{"price_per_q":35000,"yield_q_ha":15,"input_cost":40000},
    "betel_leaf":{"price_per_q":8000,"yield_q_ha":30,"input_cost":25000},
    "kola_banana":{"price_per_q":2000,"yield_q_ha":180,"input_cost":40000},
    "lai_xaak":{"price_per_q":800,"yield_q_ha":80,"input_cost":10000},
    "kosu":{"price_per_q":1200,"yield_q_ha":100,"input_cost":15000},
    "dhekia_xaak":{"price_per_q":1500,"yield_q_ha":30,"input_cost":8000},
    "manimuni":{"price_per_q":2000,"yield_q_ha":40,"input_cost":8000},
    "local_brinjal":{"price_per_q":1500,"yield_q_ha":150,"input_cost":20000},
    "local_pumpkin":{"price_per_q":800,"yield_q_ha":200,"input_cost":15000},
    "local_beans":{"price_per_q":4000,"yield_q_ha":20,"input_cost":15000},
    "bamboo_shoot":{"price_per_q":3000,"yield_q_ha":50,"input_cost":10000},
}

def get_market_forecast(crop_key):
    d = MARKET_DATA.get(crop_key.lower(),{"price_per_q":2000,"yield_q_ha":20,"input_cost":20000})
    revenue = d["price_per_q"] * d["yield_q_ha"]
    net     = revenue - d["input_cost"]
    return {"price_per_q":d["price_per_q"],"yield_q_ha":d["yield_q_ha"],"input_cost":d["input_cost"],
            "revenue":revenue,"net_profit":net,"roi_pct":round((net/d["input_cost"])*100,1)}


# ═══════════════════════════════════════════════════════════════════════════════
# PDF — single _pdf_safe, fixed with-block issue, no emoji in Helvetica
# ═══════════════════════════════════════════════════════════════════════════════
def _ensure_unicode_font():
    fp = "NotoSans-Regular.ttf"
    if not os.path.exists(fp):
        urllib.request.urlretrieve(
            "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", fp)
    return fp

def _pdf_safe(text):
    """Strip/replace anything Helvetica (Latin-1) cannot render."""
    subs = {"Rs.":"Rs.","–":"-","—":"-","\u2019":"'","\u2018":"'","\u201c":'"',"\u201d":'"'}
    for src,dst in subs.items():
        text = text.replace(src,dst)
    return "".join(c for c in text if ord(c) < 256 and c.isprintable()).strip()

def create_pdf_report(district, crop_name, confidence, temp, humidity, ph,
                      rainfall, N, P, K, fert, market, lang="en"):
    t   = UI_TEXT.get(lang, UI_TEXT["en"])
    pdf = FPDF()
    pdf.add_page()
    if lang == "as":
        fp = _ensure_unicode_font()
        pdf.add_font("NotoSans","",fp)
        pdf.add_font("NotoSans","B",fp)
        FN = FB = "NotoSans"
        def S(x): return x                  # NotoSans handles Unicode fine
    else:
        FN = FB = "Helvetica"
        def S(x): return _pdf_safe(str(x))  # strip non-latin-1

    def sn(sz=12): pdf.set_font(FN, size=sz)
    def sb(sz=12): pdf.set_font(FB, style="B" if lang=="en" else "", size=sz)

    sb(20); pdf.set_text_color(37,99,235)
    pdf.cell(0,15,S(t["pdf_report"]),ln=True,align='C'); pdf.ln(3)
    sn(12); pdf.set_text_color(0,0,0)
    pdf.cell(0,10,S(f"{t['pdf_date']}: {datetime.date.today().strftime('%B %d, %Y')}"),ln=True)
    pdf.cell(0,10,S(f"{t['pdf_location']}: {district.title()}, Assam"),ln=True); pdf.ln(3)
    sb(14); pdf.set_text_color(0,100,0)
    pdf.cell(0,10,S(f"{t['pdf_top_crop']}: {crop_name} ({confidence:.1f}% confidence)"),ln=True); pdf.ln(3)
    sb(12); pdf.set_text_color(0,0,0)
    pdf.cell(0,10,S(f"{t['pdf_env']}:"),ln=True); sn(12)
    for lbl,val in [(t['temperature'],f"{temp} C"),(t['humidity'],f"{humidity} %"),
                    (t['rainfall_mm'],f"{rainfall} mm"),(t['soil_ph'],str(ph)),
                    ("N / P / K",f"{N} | {P} | {K}")]:
        pdf.cell(0,8,S(f"  - {lbl}: {val}"),ln=True)
    pdf.ln(4)
    sb(12); pdf.set_text_color(139,69,19)
    pdf.cell(0,10,S(f"{t['pdf_fert']}:"),ln=True); sn(12); pdf.set_text_color(0,0,0)
    if fert["all_optimal"]:
        pdf.cell(0,8,S(f"  [OK] {t['fert_optimal']}"),ln=True)
    else:
        for lbl,qty in [(t['add_urea'],fert['urea_kg']),(t['add_dap'],fert['dap_kg']),(t['add_mop'],fert['mop_kg'])]:
            if qty > 0:
                pdf.cell(0,8,S(f"  - {lbl}: {qty} {t['kg_per_ha']}"),ln=True)
    pdf.ln(4)
    sb(12); pdf.set_text_color(0,70,140)
    pdf.cell(0,10,S(f"{t['pdf_market']}:"),ln=True); sn(12); pdf.set_text_color(0,0,0)
    for lbl,val in [(t['market_price'],f"Rs. {market['price_per_q']:,} / quintal"),
                    (t['market_yield'],f"{market['yield_q_ha']} quintals"),
                    (t['market_revenue'],f"Rs. {market['revenue']:,}"),
                    (t['market_cost'],f"Rs. {market['input_cost']:,}"),
                    (t['market_profit'],f"Rs. {market['net_profit']:,} (ROI: {market['roi_pct']}%)")]:
        pdf.cell(0,8,S(f"  - {lbl}: {val}"),ln=True)
    pdf.ln(10); sn(10); pdf.set_text_color(100,100,100)
    pdf.cell(0,10,S(t["pdf_footer"]),align='C')
    return bytes(pdf.output())


# ═══════════════════════════════════════════════════════════════════════════════
# WIKIPEDIA IMAGE FETCHING
# ═══════════════════════════════════════════════════════════════════════════════
_IMG_HDR = {"User-Agent":"Mozilla/5.0 Chrome/124 Safari/537","Accept":"image/*;q=0.8"}
_SKIP = ["icon","flag","map","logo","diagram","svg","symbol","coat","blank","book",
         "cover","notebook","paper","text","stamp","chart","drawing","illustration",
         "clipart","cartoon","pattern","background","wallpaper","texture","sample",
         "template","placeholder","generic","default","unknown","wiki","commons"]
_EXTS = (".jpg",".jpeg",".png",".webp")

_CROP_WIKI_TITLES = {
    "rice":"Rice","wheat":"Wheat","maize":"Maize","jute":"Jute",
    "assam_tea":"Assam_tea","coffee":"Coffea","mustard":"Mustard_plant",
    "sugarcane":"Sugarcane","cotton":"Cotton","banana":"Banana","mango":"Mango",
    "chickpea":"Chickpea","lentil":"Lentil","papaya":"Papaya","coconut":"Coconut",
    "pomegranate":"Pomegranate","grapes":"Grape","watermelon":"Watermelon",
    "muskmelon":"Cucumis_melo","orange":"Orange_(fruit)","apple":"Apple",
    "mungbean":"Mung_bean","mothbeans":"Moth_bean","pigeonpeas":"Pigeon_pea",
    "kidneybeans":"Kidney_bean","blackgram":"Vigna_mungo","joha_rice":"Joha_rice",
    "joha_rice72":"Joha_rice","bao_rice":"Boro_rice","bora_rice":"Glutinous_rice",
    "chokuwa_rice":"Chokuwa_rice","komal_saul":"Komal_saul","xaaj_rice":"Xaj_(drink)",
    "apong_rice":"Apong","bhut_jolokia":"Bhut_jolokia","kaji_nemu":"Kaji_Nemu",
    "ou_tenga":"Elephant_apple","thekera":"Garcinia_pedunculata",
    "amlokhi":"Phyllanthus_emblica","bogori":"Ziziphus_mauritiana",
    "leteku":"Baccaurea_ramiflora","jalpai":"Elaeocarpus_floribundus",
    "areca_nut":"Areca_nut","betel_leaf":"Betel","kola_banana":"Banana",
    "lai_xaak":"Brassica_juncea","kosu":"Colocasia_esculenta",
    "dhekia_xaak":"Diplazium_esculentum","manimuni":"Centella_asiatica",
    "local_brinjal":"Brinjal","local_pumpkin":"Pumpkin",
    "local_beans":"Bean","bamboo_shoot":"Bamboo_shoot",
}
_CROP_DISPLAY_NAMES = {
    "joha_rice":"Joha Rice","joha_rice72":"Joha Rice (72)","bao_rice":"Bao Rice",
    "bora_rice":"Bora Rice (Glutinous)","chokuwa_rice":"Chokuwa Rice",
    "komal_saul":"Komal Saul (Soft Rice)","xaaj_rice":"Xaaj Rice","apong_rice":"Apong Rice",
    "bhut_jolokia":"Bhut Jolokia (Ghost Pepper)","kaji_nemu":"Kaji Nemu (Assam Lemon)",
    "ou_tenga":"Ou Tenga (Elephant Apple)","thekera":"Thekera",
    "amlokhi":"Amlokhi (Indian Gooseberry)","bogori":"Bogori (Indian Jujube)",
    "leteku":"Leteku","jalpai":"Jalpai (Indian Olive)","areca_nut":"Areca Nut (Tamul)",
    "betel_leaf":"Betel Leaf (Pan)","kola_banana":"Kola Banana",
    "lai_xaak":"Lai Xaak (Mustard Greens)","kosu":"Kosu (Taro)",
    "dhekia_xaak":"Dhekia Xaak (Edible Fern)","manimuni":"Manimuni (Pennywort)",
    "local_brinjal":"Local Brinjal","local_pumpkin":"Local Pumpkin",
    "local_beans":"Local Beans","bamboo_shoot":"Bamboo Shoot","assam_tea":"Assam Tea",
}

CROP_FACTS = {
    "rice": {
        "en": "Rice is the staple food of Assam and is deeply rooted in our culture and festivals like Bihu.",
        "as": "ধান অসমৰ মুখ্য খাদ্য শস্য আৰু আমাৰ সংস্কৃতি তথা বিহুৰ দৰে উৎসৱৰ সৈতে ই ওতঃপ্ৰোতভাৱে জড়িত।"
    },
    "wheat": {
        "en": "Wheat is an important Rabi crop in Assam, providing a healthy alternative to rice in our daily diet.",
        "as": "ঘেঁহু অসমৰ এটা গুৰুত্বপূৰ্ণ ৰবি শস্য, যিয়ে আমাৰ দৈনন্দিন আহাৰত ভাতৰ এক স্বাস্থ্যকৰ বিকল্প প্ৰদান কৰে।"
    },
    "maize": {
        "en": "Maize is a versatile crop used for food, fodder, and industrial products across Assam.",
        "as": "মাকৈ এবিধ বহুমুখী শস্য যাক অসমত খাদ্য, পশুখাদ্য আৰু ঔদ্যোগিক সামগ্ৰীৰ বাবে ব্যৱহাৰ কৰা হয়।"
    },
    "jute": {
        "en": "Jute is known as the 'Golden Fiber' and is an eco-friendly crop that improves soil fertility.",
        "as": "মৰাপাটক 'সোণালী আঁহ' বুলি কোৱা হয় আৰু ই এক পৰিৱেশ অনুকূল শস্য যিয়ে মাটিৰ উৰ্বৰতা বৃদ্ধি কৰে।"
    },
    "assam_tea": {
        "en": "Assam is the world's largest tea-growing region, producing full-bodied, malty black teas.",
        "as": "অসম বিশ্বৰ সৰ্ববৃহৎ চাহ উৎপাদনকাৰী অঞ্চল, যিয়ে উন্নত মানৰ ক'লা চাহ উৎপাদন কৰে।"
    },
    "mustard": {
        "en": "Mustard is a major oilseed in Assam, painting our fields beautiful yellow during the winter.",
        "as": "সৰিয়হ অসমৰ এক প্ৰধান তৈলবীজ শস্য, যিয়ে শীতকালত আমাৰ পথাৰবোৰ হালধীয়া ৰঙেৰে সজাই তোলে।"
    },
    "sugarcane": {
        "en": "Sugarcane is widely used in Assam to produce traditional jaggery or 'Gur' during the winter months.",
        "as": "শীতকালত পৰম্পৰাগত গুৰ উৎপাদনৰ বাবে অসমত কুঁহিয়াৰৰ ব্যাপক ব্যৱহাৰ কৰা হয়।"
    },
    "cotton": {
        "en": "Cotton cultivation has a long history in the hills and plains of Assam, supporting our traditional weaving industry.",
        "as": "অসমৰ পাহাৰ আৰু ভৈয়ামত কপাহ খেতিৰ এক দীঘলীয়া ইতিহাস আছে, যিয়ে আমাৰ পৰম্পৰাগত বোৱা-কটা উদ্যোগক সহায় কৰে।"
    },
    "banana": {
        "en": "Assam has a rich diversity of bananas, including the nutrient-rich Bhim Kol variety.",
        "as": "অসমত ভীম কলৰ দৰে পুষ্টিকৰ প্ৰজাতিৰ লগতে বিভিন্ন প্ৰকাৰৰ কল পোৱা যায়।"
    },
    "mango": {
        "en": "Assamese mangoes are known for their sweet aroma and variety, often used in making traditional pickles.",
        "as": "অসমৰ আম ইয়াৰ মিঠা সুবাস আৰু বিভিন্ন প্ৰকাৰৰ বাবে জনাজাত, যিবোৰ প্ৰায়ে পৰম্পৰাগত আচাৰ বনাবলৈ ব্যৱহাৰ কৰা হয়।"
    },
    "chickpea": {
        "en": "Chickpeas are a valuable source of protein and are grown as a Rabi crop in the drier regions of Assam.",
        "as": "বুট মাহ প্ৰটিনৰ এক মূল্যৱান উৎস আৰু অসমৰ শুকান অঞ্চলবোৰত ৰবি শস্য হিচাপে খেতি কৰা হয়।"
    },
    "lentil": {
        "en": "Lentils or 'Masur Dal' are a common part of the Assamese meal, rich in fiber and protein.",
        "as": "মচুৰ মাহ অসমীয়া আহাৰৰ এক সাধাৰণ অংশ, যি ফাইবাৰ আৰু প্ৰটিনত চহকী।"
    },
    "papaya": {
        "en": "Papaya grows easily in the backyards of Assam and is used both as a fruit and a vegetable in traditional dishes like Khar.",
        "as": "অমিতা অসমৰ বাৰীত সহজে গজে আৰু ইয়াক ফল তথা খাৰৰ দৰে পৰম্পৰাগত ব্যঞ্জনত পাছলি হিচাপেও ব্যৱহাৰ কৰা হয়।"
    },
    "coconut": {
        "en": "Coconut trees are common in lower Assam, providing water, oil, and ingredients for traditional sweets like Laroo.",
        "as": "নামনি অসমত নাৰিকল গছ অতি সুলভ, যাৰ পৰা পানী, তেল আৰু লাডুৰ দৰে পৰম্পৰাগত মিঠাইৰ বাবে উপাদান পোৱা যায়।"
    },
    "pomegranate": {
        "en": "Pomegranates are increasingly grown in home gardens in Assam for their health-boosting antioxidants.",
        "as": "স্বাস্থ্যৰ বাবে উপকাৰী এন্টিঅক্সিডেন্টৰ বাবে অসমৰ ঘৰুৱা বাগিচাবোৰত ডালিমৰ খেতি বৃদ্ধি পাইছে।"
    },
    "grapes": {
        "en": "Grape cultivation is being explored in certain micro-climates of Assam as a high-value horticultural crop.",
        "as": "অসমৰ কিছুমান বিশেষ জলবায়ু অঞ্চলত এক উচ্চ মূল্যৰ উদ্যান শস্য হিচাপে আঙুৰ খেতিৰ সম্ভাৱনীয়তা পৰীক্ষা কৰা হৈছে।"
    },
    "watermelon": {
        "en": "Watermelons from the riverine 'Char' areas of Assam are highly sought after during the hot summer months.",
        "as": "অসমৰ চৰ অঞ্চলৰ তৰমুজ গৰমৰ দিনবোৰত অতি জনপ্ৰিয়।"
    },
    "muskmelon": {
        "en": "Muskmelons are grown in the sandy soils of the Brahmaputra valley, offering a refreshing summer treat.",
        "as": "ব্ৰহ্মপুত্ৰ উপত্যকাৰ বালিচহীয়া মাটিত ফুটি খেতি কৰা হয়, যি গৰমৰ দিনত এক সতেজতা প্ৰদান কৰে।"
    },
    "orange": {
        "en": "The oranges of Kamrup and Tinsukia districts are famous for their juicy sweetness and vibrant color.",
        "as": "কামৰূপ আৰু তিনিচুকীয়া জিলাৰ সুমথিৰা টেঙা ইয়াৰ ৰসাল সোৱাদ আৰু উজ্জ্বল ৰঙৰ বাবে বিখ্যাত।"
    },
    "apple": {
        "en": "Apples are being trial-grown in the higher altitudes of Dima Hasao and Karbi Anglong districts.",
        "as": "ডিমা হাছাও আৰু কাৰ্বি আংলং জিলাৰ ওখ অঞ্চলবোৰত আপেলৰ পৰীক্ষামূলক খেতি কৰা হৈছে।"
    },
    "mungbean": {
        "en": "Mung beans or 'Mogu Mah' are light and nutritious, often served during religious and social gatherings.",
        "as": "মগু মাহ পাতল আৰু পুষ্টিকৰ, যি প্ৰায়ে ধৰ্মীয় আৰু সামাজিক অনুষ্ঠানবোৰত পৰিৱেশন কৰা হয়।"
    },
    "mothbeans": {
        "en": "Moth beans are drought-resistant pulses that can grow in the drier patches of the state.",
        "as": "মথ বীন হ'ল খৰাং প্ৰতিৰোধী মাহজাতীয় শস্য যি ৰাজ্যখনৰ শুকান অঞ্চলবোৰত গজিব পাৰে।"
    },
    "pigeonpeas": {
        "en": "Pigeon peas or 'Arhar Dal' are a sturdy crop providing essential nutrients to the rural population.",
        "as": "অৰহৰ মাহ এবিধ শক্তিশালী শস্য যিয়ে গ্ৰাম্য জনসংখ্যাক প্ৰয়োজনীয় পুষ্টি প্ৰদান কৰে।"
    },
    "kidneybeans": {
        "en": "Kidney beans or 'Rajma' are grown in the hilly terrains of Assam and are loved for their rich taste.",
        "as": "ৰাজমাহ অসমৰ পাহাৰীয়া অঞ্চলত খেতি কৰা হয় আৰু ইয়াৰ সোৱাদৰ বাবে সকলোৱে ভাল পায়।"
    },
    "blackgram": {
        "en": "Black gram or 'Mati Mah' is an essential ingredient for the traditional Assamese Khar dish.",
        "as": "মাটি মাহ অসমীয়াৰ পৰম্পৰাগত খাৰ ব্যঞ্জনৰ এক অপৰিহাৰ্য উপাদান।"
    },
    "coffee": {
        "en": "Coffee cultivation is gaining momentum in the hill districts of Assam, offering a new livelihood option.",
        "as": "অসমৰ পাহাৰীয়া জিলাবোৰত কফি খেতিয়ে জনপ্ৰিয়তা লাভ কৰিছে, যি এক নতুন জীৱিকাৰ পথ মুকলি কৰিছে।"
    },
    "joha_rice": {
        "en": "Joha rice is a unique aromatic rice variety of Assam, known for its exquisite taste and scent.",
        "as": "জোহা ধান অসমৰ এক অনন্য সুগন্ধি ধানৰ প্ৰজাতি, যি ইয়াৰ সুস্বাদু সোৱাদ আৰু সুবাসৰ বাবে জনাজাত।"
    },
    "joha_rice72": {
        "en": "Joha Rice 72 is an improved variety that retains the classic aroma while offering better yields.",
        "as": "জোহা ধান ৭২ হ'ল এক উন্নত প্ৰজাতি যিয়ে পৰম্পৰাগত সুবাস অটুট ৰখাৰ লগতে অধিক উৎপাদন প্ৰদান কৰে।"
    },
    "bao_rice": {
        "en": "Bao rice is a deep-water paddy variety that can grow even during the high floods of Assam.",
        "as": "বাও ধান হ'ল এক দ-পানীৰ ধানৰ প্ৰজাতি যি অসমৰ বৰষুণ আৰু বানপানীৰ মাজতো গজিব পাৰে।"
    },
    "bora_rice": {
        "en": "Bora rice is a glutinous variety used to make traditional Pithas and Jolpan in Assamese households.",
        "as": "বৰা ধান হ'ল এবিধ আঠাযুক্ত ধান যাৰ পৰা অসমীয়া উৰহৰ পিঠা আৰু জলপান তৈয়াৰ কৰা হয়।"
    },
    "chokuwa_rice": {
        "en": "Chokuwa rice, also known as 'Magic Rice', is unique because it can be eaten just by soaking in water.",
        "as": "চকুৱা ধান বা 'ম্যাজিক ৰাইচ'ৰ বৈশিষ্ট্য হ'ল ইয়াক কেৱল পানীত তিয়াই থৈয়ে খাব পাৰি।"
    },
    "komal_saul": {
        "en": "Komal Saul is a specially processed rice that becomes soft and edible when soaked, requiring no cooking.",
        "as": "কোমল চাউল হ'ল এক বিশেষভাৱে প্ৰস্তুত কৰা চাউল যাক সিজোৱাৰ প্ৰয়োজন নাই, কেৱল তিয়াই থৈ খাব পাৰি।"
    },
    "xaaj_rice": {
        "en": "Xaaj rice is a traditional variety used primarily in the brewing of indigenous Assamese rice beer.",
        "as": "সাঁজ ধান হ'ল এক পৰম্পৰাগত ধানৰ প্ৰজাতি যাক মূলতঃ থলুৱা অসমীয়া লাওপানী বা সাঁজ প্ৰস্তুত কৰিবলৈ ব্যৱহাৰ কৰা হয়।"
    },
    "apong_rice": {
        "en": "Apong rice is a specialty variety used by tribal communities for preparing traditional ceremonial drinks.",
        "as": "আপং ধান হ'ল এক বিশেষ ধানৰ প্ৰজাতি যি জনজাতীয় সম্প্ৰদায়ৰ মাজত পৰম্পৰাগত পানীয় প্ৰস্তুত কৰিবলৈ ব্যৱহাৰ কৰা হয়।"
    },
    "bhut_jolokia": {
        "en": "Bhut Jolokia is one of the world's hottest chili peppers and is native to Northeast India.",
        "as": "ভোট জলকীয়া বিশ্বৰ অন্যতম জ্বলা জলকীয়া আৰু ই উত্তৰ-পূব ভাৰতৰ থলুৱা প্ৰজাতি।"
    },
    "kaji_nemu": {
        "en": "Kaji Nemu is the state fruit of Assam, famous for its unique scent and high juice content.",
        "as": "কাজী নেমু অসমৰ ৰাজ্যিক ফল, যি ইয়াৰ অনন্য সুবাস আৰু অধিক ৰসৰ বাবে বিখ্যাত।"
    },
    "ou_tenga": {
        "en": "Ou Tenga or Elephant Apple is a sour fruit used in Assamese fish curries and dal for its tangy flavor.",
        "as": "ঔ টেঙা হ'ল এবিধ টেঙা ফল যাক ইয়াৰ বিশেষ সোৱাদৰ বাবে মাছৰ আঞ্জা আৰু দাইলত ব্যৱহাৰ কৰা হয়।"
    },
    "thekera": {
        "en": "Thekera is a dried sour fruit used as a natural coolant and for its medicinal properties in Assamese cuisine.",
        "as": "থেকেৰা হ'ল এবিধ শুকুৱাই ৰখা টেঙা ফল যাক প্ৰাকৃতিক শীতলকাৰক হিচাপে আৰু ইয়াৰ ঔষধি গুণৰ বাবে ব্যৱহাৰ কৰা হয়।"
    },
    "amlokhi": {
        "en": "Amlokhi or Indian Gooseberry is a powerhouse of Vitamin C, often used in pickles and traditional medicine.",
        "as": "আমলখি হ'ল ভিটামিন চি-ৰ এক ভাণ্ডাৰ, যাক প্ৰায়ে আচাৰ আৰু পৰম্পৰাগত ঔষধত ব্যৱহাৰ কৰা হয়।"
    },
    "bogori": {
        "en": "Bogori or Indian Jujube is a popular seasonal fruit in Assam, loved in both raw and pickled forms.",
        "as": "বগৰী অসমৰ এক জনপ্ৰিয় ঋতুভিত্তিক ফল, যাক কেঁচাই বা আচাৰ হিচাপে খোৱা হয়।"
    },
    "leteku": {
        "en": "Leteku is a small, sweet and sour wild fruit found in the forests of Assam during the summer.",
        "as": "লেতেকু হ'ল অসমৰ হাবিত পোৱা এবিধ সৰু, মিঠা-টেঙা বনৰীয়া ফল যি গ্ৰীষ্মকালত উপলব্ধ হয়।"
    },
    "jalpai": {
        "en": "Jalpai or Indian Olive is a tangy fruit used to make delicious sweet and sour pickles in Assam.",
        "as": "জলফাই হ'ল এবিধ টেঙা ফল যাৰ পৰা অসমত সুস্বাদু মিঠা-টেঙা আচাৰ তৈয়াৰ কৰা হয়।"
    },
    "areca_nut": {
        "en": "Areca nut or 'Tamul' is a symbol of hospitality in Assam, always offered to guests with betel leaf.",
        "as": "তামোল অসমীয়া অতিথি পৰায়ণতাৰ প্ৰতীক, যি সদায় আলহীক পাণৰ সৈতে আগবঢ়োৱা হয়।"
    },
    "betel_leaf": {
        "en": "Betel leaf or 'Paan' is an integral part of Assamese social life and traditional rituals.",
        "as": "পাণ অসমীয়া সামাজিক জীৱন আৰু পৰম্পৰাগত ৰীতি-নীতিৰ এক অবিচ্ছেদ্য অংশ।"
    },
    "kola_banana": {
        "en": "Kola Banana is a local variety whose skin is burned to make 'Kharola', a key ingredient in traditional Khar.",
        "as": "কোলা কল হ'ল এক থলুৱা প্ৰজাতি যাৰ বাকলি পুৰি 'খাৰণি' তৈয়াৰ কৰা হয়, যি খাৰ ব্যঞ্জনৰ এক মুখ্য উপাদান।"
    },
    "lai_xaak": {
        "en": "Lai Xaak or Mustard Greens are a winter favorite in Assam, often cooked with pork or small fish.",
        "as": "লাই শাক শীতকালত অসমৰ এক প্ৰিয় খাদ্য, যাক প্ৰায়ে গাহৰিৰ মাংস বা সৰু মাছৰ সৈতে ৰন্ধা হয়।"
    },
    "kosu": {
        "en": "Kosu or Taro is a versatile vegetable in Assam, with its leaves, stems, and roots all being edible.",
        "as": "কচু অসমৰ এক বহুমুখী পাছলি, যাৰ পাত, ঠাৰি আৰু শিপা সকলো খাব পাৰি।"
    },
    "dhekia_xaak": {
        "en": "Dhekia Xaak is an edible fern collected from the wild, known for its crisp texture and health benefits.",
        "as": "ঢেকীয়া শাক হ'ল হাবিত পোৱা এবিধ বনশাক, যি ইয়াৰ কুৰকুৰীয়া সোৱাদ আৰু স্বাস্থ্যকৰ গুণৰ বাবে জনাজাত।"
    },
    "manimuni": {
        "en": "Manimuni or Pennywort is a medicinal herb used in Assamese households to treat stomach ailments.",
        "as": "মণিমুনি হ'ল এবিধ ঔষধি গুণসম্পন্ন বনশাক যাক পেটৰ অসুখ নিৰাময়ৰ বাবে ব্যৱহাৰ কৰা হয়।"
    },
    "local_brinjal": {
        "en": "Local brinjals in Assam come in various shapes and sizes, celebrated for their tender taste in pitikas.",
        "as": "অসমৰ থলুৱা বেঙেনা বিভিন্ন আকাৰৰ পোৱা যায় আৰু ই পিটিকাত বহুত সোৱাদ দিয়ে।"
    },
    "local_pumpkin": {
        "en": "Local pumpkins are grown in almost every rural backyard in Assam, used in various sweet and savory dishes.",
        "as": "অসমৰ প্ৰতিখন গাঁৱৰে বাৰীত ৰঙালাউ খেতি কৰা হয়, যাক বিভিন্ন মিঠা আৰু জ্বলা ব্যঞ্জনত ব্যৱহাৰ কৰা হয়।"
    },
    "local_beans": {
        "en": "Local beans are a rich source of protein and are a common sight in the winter vegetable markets of Assam.",
        "as": "থলুৱা লেচেৰা বা বীন প্ৰটিনৰ এক চহকী উৎস আৰু অসমৰ শীতকালীন বজাৰত যথেষ্ট পৰিমাণে পোৱা যায়।"
    },
    "bamboo_shoot": {
        "en": "Bamboo shoots or 'Khorisa' are a delicacy in Assam, adding a unique fermented flavor to meats and curries.",
        "as": "বাঁহৰ গাজ বা 'খৰিচা' অসমীয়া খাদ্যৰ এক বিশেষ সোৱাদ, যিয়ে মাংস আৰু আঞ্জাত এক সুকীয়া আমেজ প্ৰদান কৰে।"
    }
}
def get_display_name(k): return _CROP_DISPLAY_NAMES.get(k, k.replace("_"," ").title())

def _get_img(url):
    try:
        r=requests.get(url,headers=_IMG_HDR,timeout=10,verify=False,allow_redirects=True)
        if r.status_code==200 and "image" in r.headers.get("Content-Type","") and len(r.content)>10000:
            return r.content
    except Exception: pass
    return None

def _clean_url(url):
    u=url.lower()
    if not any(u.endswith(e) or (e+"?") in u for e in _EXTS): return False
    return not any(kw in u for kw in _SKIP)

def _wiki_infobox(crop_key):
    title=_CROP_WIKI_TITLES.get(crop_key.lower())
    if not title: return None
    try:
        r=requests.get(f"https://en.wikipedia.org/w/api.php?action=query&titles={title}"
                       "&prop=pageimages&pithumbsize=600&format=json&origin=*",
                       headers={"User-Agent":"AssamCropRecommender/4.0"},timeout=10,verify=False)
        if r.status_code==200:
            for page in r.json().get("query",{}).get("pages",{}).values():
                thumb=page.get("thumbnail",{}).get("source","")
                if thumb:
                    img=_get_img(thumb)
                    if img: return img
    except Exception: pass
    return None

def _wiki_search(crop_name):
    q=urllib.parse.quote(f"{crop_name} crop plant field")
    try:
        r=requests.get(f"https://commons.wikimedia.org/w/api.php?action=query&generator=search"
                       f"&gsrnamespace=6&gsrsearch={q}&prop=imageinfo&iiprop=url&iiurlwidth=600"
                       "&format=json&origin=*&gsrlimit=25",
                       headers={"User-Agent":"AssamCropRecommender/4.0"},timeout=10,verify=False)
        if r.status_code==200:
            for page in r.json().get("query",{}).get("pages",{}).values():
                info=page.get("imageinfo",[{}])[0]
                thumb=info.get("thumburl") or info.get("url","")
                if thumb and _clean_url(thumb):
                    img=_get_img(thumb)
                    if img: return img
    except Exception: pass
    return None

def _placeholder(crop_name):
    from PIL import ImageDraw, ImageFont
    W,H=800,600; img=Image.new("RGB",(W,H)); draw=ImageDraw.Draw(img)
    for y in range(H):
        t=y/H
        draw.line([(0,y),(W,y)],fill=(int(26+(45-26)*t),int(71+(106-71)*t),int(42+(79-42)*t)))
    label=crop_name.replace("_"," ").title()
    initials="".join(w[0].upper() for w in label.split()[:2])
    try: fb=ImageFont.truetype("arial.ttf",80); fm=ImageFont.truetype("arial.ttf",52); fs=ImageFont.truetype("arial.ttf",24)
    except: fb=fm=fs=ImageFont.load_default()
    draw.text((W//2,H//2-80),initials,font=fb,fill=(255,255,255,30),anchor="mm")
    draw.text((W//2,H//2+20),label,font=fm,fill=(255,255,255),anchor="mm")
    draw.text((W//2,H//2+90),"No photo available",font=fs,fill=(180,220,180),anchor="mm")
    buf=BytesIO(); img.save(buf,format="PNG"); return buf.getvalue()

@st.cache_data(ttl=86400, show_spinner=False)
def fetch_crop_image(crop_name):
    key = crop_name.lower().replace(" ","_")
    
    # 1. Check local images folder first
    for ext in [".jpg", ".jpeg", ".png", ".webp"]:
        local_path = os.path.join("images", f"{key}{ext}")
        if os.path.exists(local_path):
            try:
                with open(local_path, "rb") as f:
                    return f.read(), True
            except Exception:
                pass

    # 2. Fallback to Wikipedia
    img = _wiki_infobox(key)
    if img: return img, True
    img = _wiki_search(crop_name)
    if img: return img, True
    
    # 3. Placeholder
    return _placeholder(crop_name), False


# ─── Model & Crop Info ────────────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def load_models():
    return (pickle.load(open("model/crop_model.pkl","rb")),
            pickle.load(open("model/label_encoder.pkl","rb")))

CROP_INFO = {
    "rice":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "wheat":{"season":"Rabi (Nov-Apr)","water":"Medium","icon":"🌿"},
    "maize":{"season":"Kharif / Rabi","water":"Medium","icon":"🌽"},
    "jute":{"season":"Kharif (Mar-Jul)","water":"High","icon":"🌱"},
    "assam_tea":{"season":"Year-round","water":"High","icon":"🍵"},
    "mustard":{"season":"Rabi (Oct-Mar)","water":"Low","icon":"🌼"},
    "sugarcane":{"season":"Year-round","water":"High","icon":"🎋"},
    "cotton":{"season":"Kharif (Apr-Nov)","water":"Medium","icon":"☁️"},
    "banana":{"season":"Year-round","water":"Medium","icon":"🍌"},
    "mango":{"season":"Summer (Mar-Jun)","water":"Low","icon":"🥭"},
    "chickpea":{"season":"Rabi (Oct-Mar)","water":"Low","icon":"🫘"},
    "lentil":{"season":"Rabi (Oct-Mar)","water":"Low","icon":"🫘"},
    "papaya":{"season":"Year-round","water":"Medium","icon":"🍈"},
    "coconut":{"season":"Year-round","water":"High","icon":"🥥"},
    "pomegranate":{"season":"Summer / Winter","water":"Low","icon":"🍎"},
    "grapes":{"season":"Winter (Oct-Feb)","water":"Medium","icon":"🍇"},
    "watermelon":{"season":"Summer (Mar-Jun)","water":"Low","icon":"🍉"},
    "muskmelon":{"season":"Summer (Feb-May)","water":"Low","icon":"🍈"},
    "orange":{"season":"Winter (Dec-Feb)","water":"Medium","icon":"🍊"},
    "apple":{"season":"Summer (Jun-Sep)","water":"Medium","icon":"🍎"},
    "mungbean":{"season":"Kharif / Summer","water":"Low","icon":"🫘"},
    "mothbeans":{"season":"Kharif (Jun-Sep)","water":"Low","icon":"🫘"},
    "pigeonpeas":{"season":"Kharif (Jun-Nov)","water":"Low","icon":"🫘"},
    "kidneybeans":{"season":"Kharif (Jun-Sep)","water":"Medium","icon":"🫘"},
    "blackgram":{"season":"Kharif / Rabi","water":"Low","icon":"🫘"},
    "coffee":{"season":"Year-round","water":"Medium","icon":"☕"},
    "joha_rice":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "joha_rice72":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "bao_rice":{"season":"Kharif (Jun-Dec)","water":"High","icon":"🌾"},
    "bora_rice":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "chokuwa_rice":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "komal_saul":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "xaaj_rice":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "apong_rice":{"season":"Kharif (Jun-Nov)","water":"High","icon":"🌾"},
    "bhut_jolokia":{"season":"Kharif (Jul-Oct)","water":"Medium","icon":"🌶️"},
    "kaji_nemu":{"season":"Year-round","water":"Medium","icon":"🍋"},
    "ou_tenga":{"season":"Monsoon (Jun-Sep)","water":"Medium","icon":"🍏"},
    "thekera":{"season":"Monsoon (Jun-Sep)","water":"Medium","icon":"🍋"},
    "amlokhi":{"season":"Rabi (Oct-Feb)","water":"Low","icon":"🟢"},
    "bogori":{"season":"Winter (Oct-Jan)","water":"Low","icon":"🫐"},
    "leteku":{"season":"Summer (Apr-Jun)","water":"Medium","icon":"🍇"},
    "jalpai":{"season":"Monsoon (Jul-Sep)","water":"Medium","icon":"🫒"},
    "areca_nut":{"season":"Year-round","water":"High","icon":"🌴"},
    "betel_leaf":{"season":"Year-round","water":"High","icon":"🍃"},
    "kola_banana":{"season":"Year-round","water":"Medium","icon":"🍌"},
    "lai_xaak":{"season":"Rabi (Oct-Feb)","water":"Medium","icon":"🥬"},
    "kosu":{"season":"Year-round","water":"High","icon":"🌿"},
    "dhekia_xaak":{"season":"Monsoon (Jun-Sep)","water":"High","icon":"🌿"},
    "manimuni":{"season":"Year-round","water":"Medium","icon":"🌿"},
    "local_brinjal":{"season":"Year-round","water":"Medium","icon":"🍆"},
    "local_pumpkin":{"season":"Kharif (Jun-Oct)","water":"Medium","icon":"🎃"},
    "local_beans":{"season":"Kharif / Rabi","water":"Medium","icon":"🫘"},
    "bamboo_shoot":{"season":"Monsoon (Jun-Aug)","water":"High","icon":"🎍"},
}
def get_crop_info(k): return CROP_INFO.get(k.lower(),{"season":"—","water":"—","icon":"🌱"})


# ═══════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ═══════════════════════════════════════════════════════════════════════════════
if "lang" not in st.session_state:
    st.session_state["lang"] = "en"

with st.sidebar:
    st.markdown("""
    <div style="background:linear-gradient(135deg,#1e3a8a,#2563eb);padding:18px 16px;
         border-radius:12px;margin-bottom:12px;text-align:center;">
      <div style="font-size:28px;margin-bottom:4px;">🌾</div>
      <div style="color:white;font-size:16px;font-weight:600;letter-spacing:.5px;">Assam Crop Advisor</div>
      <div style="color:rgba(255,255,255,.6);font-size:11px;margin-top:2px;">Right crop, right time, maximum yield.</div>
    </div>""", unsafe_allow_html=True)

    st.radio(T("lang_toggle"), options=["en","as"],
             format_func=lambda x:"🇬🇧 English" if x=="en" else "🇮🇳 অসমীয়া",
             horizontal=True, key="lang")
    st.divider()

    with st.expander(f"📍 {T('location_hdr')}", expanded=True):
        _ASSAM_LOCATIONS = [
            "Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", 
            "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", 
            "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup", 
            "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar", 
            "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", 
            "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong",
            "Guwahati", "Silchar", "Tezpur", "Diphu"
        ]
        district = st.selectbox(T("district"), options=sorted(_ASSAM_LOCATIONS), index=sorted(_ASSAM_LOCATIONS).index("Guwahati"),
                                  help="Used to fetch live temperature & humidity")

    with st.expander(f"⚙️ {T('input_mode_hdr')}", expanded=True):
        input_mode = st.radio(T("input_mode"), [T("simple"), T("advanced")], label_visibility="collapsed")

    with st.expander(f"📊 {T('display_opts')}", expanded=False):
        show_dashboard = st.toggle(T("show_dash"), value=True)
        show_history   = st.toggle(T("show_history"), value=False)
        top_n          = st.slider(T("num_recs"), 3, 7, 3)

    st.divider()

    with st.expander(f"📷 {T('cam_header')}", expanded=False):
        use_cam = st.toggle(T("cam_toggle"), value=False)
        cam_img = None
        if use_cam:
            cam_img = st.camera_input(T("cam_take"))
        
        up_img = st.file_uploader(
            T("cam_upload"), type=["jpg","jpeg","png","webp"], key="cam_upload_widget")
        
        final_img = cam_img or up_img
        if final_img:
            with st.spinner(T("cam_detecting")):
                result = identify_crop_from_image(final_img.getvalue())
            if result["confidence"] > 0 and result["crop_key"] != "unknown":
                st.success(f"{T('cam_detected')}: **{result['display_name']}** ({result['confidence']}%)")
                if result.get("disease"):
                    st.warning(f"Possible issue: {result['disease']}")
                if result.get("notes"):
                    st.info(result["notes"])
                st.session_state["detected_crop"] = result["crop_key"]
            else:
                st.warning(result.get("notes", T("cam_error")))


# ═══════════════════════════════════════════════════════════════════════════════
# UPGRADED CSS
# ═══════════════════════════════════════════════════════════════════════════════
st.markdown("""<style>
/* ── Global ── */
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');
html, body, [class*="css"] { font-family: 'Plus Jakarta Sans', sans-serif; }

/* ── Main crop card ── */
.crop-card {
    background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%);
    border-radius: 20px; padding: 2rem 2.25rem; color: #0f172a; margin: 1rem 0;
    border: 1px solid #bae6fd;
    box-shadow: 0 4px 20px rgba(0,0,0,.05);
    position: relative; overflow: hidden;
}
.crop-card::before {
    content:""; position:absolute; top:-60px; right:-60px;
    width:200px; height:200px; border-radius:50%;
    background:rgba(37,99,235,.03);
}
.crop-card::after {
    content:""; position:absolute; bottom:-80px; left:30%;
    width:300px; height:300px; border-radius:50%;
    background:rgba(37,99,235,.02);
}
.crop-card .badge {
    display:inline-block; background:rgba(37,99,235,.1);
    border:1px solid rgba(37,99,235,.2); border-radius:30px;
    padding:4px 14px; font-size:11px; font-weight:600;
    letter-spacing:.08em; text-transform:uppercase; margin-bottom:12px;
    color: #2563eb;
}
.crop-card h2 { margin:0 0 .35rem 0; font-size:2.2rem; font-weight:700; line-height:1.2; }
.crop-card p  { margin:0; opacity:.75; font-size:.92rem; }

/* ── Metric pills ── */
.metric-pill {
    display:inline-flex; align-items:center; gap:.4rem;
    background:rgba(37,99,235,.10); border:1px solid rgba(37,99,235,.22);
    border-radius:30px; padding:.4rem 1rem;
    font-size:.82rem; font-weight:500; margin:3px 2px;
    transition: background .2s;
}
.metric-pill:hover { background:rgba(37,99,235,.18); }

/* ── Section cards ── */
.section-card {
    background: var(--background-color, #ffffff);
    border: 1px solid rgba(0,0,0,.07);
    border-radius: 16px; padding: 1.25rem 1.5rem; margin: .75rem 0;
}

/* ── Fert & market cards ── */
.fert-card {
    background:rgba(139,69,19,.05); border-left:3px solid #c0722a;
    border-radius:0 14px 14px 0; padding:1.25rem 1.5rem; margin:.75rem 0;
}
.market-card {
    background:rgba(0,70,140,.04); border-left:3px solid #2463ae;
    border-radius:0 14px 14px 0; padding:1.25rem 1.5rem; margin:.75rem 0;
}

/* ── Alert banner ── */
.alert-banner {
    border-left:3px solid #e6a817;
    background:linear-gradient(90deg,rgba(230,168,23,.08),transparent);
    border-radius:0 10px 10px 0; padding:.8rem 1.1rem; font-size:.88rem; margin:.5rem 0;
}

/* ── Stat row inside market card ── */
.stat-row {
    display:flex; justify-content:space-between; align-items:center;
    padding:.5rem 0; border-bottom:1px solid rgba(0,0,0,.06);
    font-size:.88rem;
}
.stat-row:last-child { border-bottom:none; }
.stat-label { color:#666; }
.stat-value { font-weight:600; color:#1e3a8a; }
.stat-value.profit { color:#1a6b3c; font-size:1.05rem; }
.stat-value.cost   { color:#b03a2e; }

/* ── Confidence bar ── */
.conf-bar-wrap { margin-top:8px; }
.conf-bar-bg { background:#eff6ff; border-radius:8px; height:10px; overflow:hidden; }
.conf-bar-fill { background:linear-gradient(90deg,#2563eb,#60a5fa); height:10px; border-radius:8px; transition:width .8s ease; }

/* ── Sidebar tweaks ── */
section[data-testid="stSidebar"] > div { padding-top: 1rem !important; }

/* ── Hide Streamlit footer ── */
footer { visibility:hidden; }
#MainMenu { visibility:hidden; }
</style>""", unsafe_allow_html=True)


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN CONTENT
# ═══════════════════════════════════════════════════════════════════════════════
st.markdown(f"""
<div style="padding:.5rem 0 1.5rem;">
  <h1 style="font-size:1.9rem;font-weight:700;margin:0 0 .25rem;">{T('title')}</h1>
  <p style="color:#666;margin:0;font-size:.95rem;">{T('subtitle')}</p>
</div>""", unsafe_allow_html=True)

st.markdown(f"### {T('soil_header')}")
simple_mode = T("simple") in input_mode

if simple_mode:
    col1, col2 = st.columns(2)
    with col1:
        soil_type = st.selectbox(T("soil_type"), list(soil_properties.keys()), format_func=T)
        ph_v = soil_properties[soil_type]['ph']
        st.markdown(f'<div style="font-size:.82rem;color:#666;margin-top:4px;">'
                    f'pH {ph_v} &nbsp;·&nbsp; N={soil_properties[soil_type]["N"]} '
                    f'&nbsp;·&nbsp; P={soil_properties[soil_type]["P"]} '
                    f'&nbsp;·&nbsp; K={soil_properties[soil_type]["K"]}</div>', unsafe_allow_html=True)
    with col2:
        season = st.selectbox(T("season"), list(season_rainfall.keys()), format_func=T)
        st.markdown(f'<div style="font-size:.82rem;color:#666;margin-top:4px;">'
                    f'{T("exp_rainfall_prefix")} {season_rainfall[season]} {T("exp_rainfall_suffix")}</div>', unsafe_allow_html=True)

    detected = st.session_state.get("detected_crop")
    if detected and detected != "unknown":
        st.info(f"{T('cam_pre_filled')} **{get_display_name(detected)}** — switch to Advanced Mode to use exact values.")

    N  = soil_properties[soil_type]["N"]
    P  = soil_properties[soil_type]["P"]
    K  = soil_properties[soil_type]["K"]
    ph = soil_properties[soil_type]["ph"]
    rainfall = season_rainfall[season]
else:
    st.info("Enter your soil lab test results. Weather is fetched automatically.")
    c1, c2, c3 = st.columns(3)
    with c1:
        N  = st.number_input(T("nitrogen"),  0, 150, 50)
        ph = st.slider(T("soil_ph"), 3.0, 9.0, 6.5, 0.1)
    with c2:
        P        = st.number_input(T("phosphorus"), 0, 150, 50)
        rainfall = st.number_input(T("rainfall_mm"), 0.0, 500.0, 200.0)
    with c3:
        K = st.number_input(T("potassium"), 0, 150, 50)
    npk_sum = N + P + K
    if npk_sum > 0 and (N/npk_sum) > 0.6:
        st.markdown('<div class="alert-banner">⚠️ High nitrogen — may favour leafy crops over fruiting ones.</div>', unsafe_allow_html=True)
    if ph < 4.5:
        st.markdown('<div class="alert-banner">⚠️ Highly acidic (pH < 4.5). Consider liming before planting.</div>', unsafe_allow_html=True)
    elif ph > 8.0:
        st.markdown('<div class="alert-banner">⚠️ Alkaline soil (pH > 8). May limit nutrient uptake.</div>', unsafe_allow_html=True)

st.markdown("")
predict_btn = st.button(T("predict_btn"), type="primary", use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# RESULTS
# ═══════════════════════════════════════════════════════════════════════════════
if predict_btn:
    with st.spinner(T("fetching")):
        try:
            rf_model, label_encoder = load_models()
        except FileNotFoundError:
            st.error(T("model_not_found")); st.stop()
        temp, humidity, status = get_live_weather(district)
        if temp is None:
            st.error(f"{T('weather_error')}: {status}"); st.stop()
        features      = np.array([[N, P, K, temp, humidity, ph, rainfall]])
        probabilities = rf_model.predict_proba(features)[0]
        top_n_indices = np.argsort(probabilities)[::-1][:top_n]
        top_n_probs   = probabilities[top_n_indices]
        top_n_crops   = label_encoder.inverse_transform(top_n_indices)

    st.success(T("analysis_done"))
    st.divider()

    best_crop  = top_n_crops[0]
    best_label = get_display_name(best_crop)
    best_conf  = top_n_probs[0] * 100
    crop_info  = get_crop_info(best_crop)
    image_data, is_real = fetch_crop_image(best_crop)

    # ── Top recommendation card ───────────────────────────────────────────────
    st.markdown(f"""
    <div class="crop-card">
      <div class="badge">{T('top_rec')} &nbsp;·&nbsp; {best_conf:.1f}% confidence</div>
      <h2>{crop_info['icon']} {best_label}</h2>
      <p>{T('best_fit')} {district} — {T('best_fit2')}</p>
    </div>""", unsafe_allow_html=True)

    img_col, info_col = st.columns([1, 2])
    with img_col:
        st.image(image_data, use_container_width=True,
                 caption=T("real_photo") if is_real else f"{crop_info['icon']} {best_label}")

    with info_col:
        st.markdown(
            f'<span class="metric-pill">📅 {crop_info["season"]}</span>'
            f'<span class="metric-pill">💧 {T("water_need")}: {crop_info["water"]}</span>'
            f'<span class="metric-pill">🌡️ {temp}°C</span>'
            f'<span class="metric-pill">💦 {humidity}% humidity</span>',
            unsafe_allow_html=True)
        st.markdown("")
        pct = int(best_conf)
        st.markdown(f"""
        <div class="conf-bar-wrap">
          <div style="font-size:.82rem;color:#555;margin-bottom:5px;">{T('confidence')}: <strong>{best_conf:.1f}%</strong></div>
          <div class="conf-bar-bg"><div class="conf-bar-fill" style="width:{pct}%;"></div></div>
        </div>""", unsafe_allow_html=True)
        st.markdown("")
        st.markdown(f"**{T('why_crop')}**")
        st.markdown(f"{T('ai_matched')} **{best_label}** {T('based_on')} {ph}, "
                    f"N={N}/P={P}/K={K}. {T('live_weather')} {district}: "
                    f"{temp}°C, {humidity}%, {rainfall} {T('exp_rainfall')} {T('hist_align')}")

        # TTS
        fert_preview   = calculate_fertilizer_prescription(best_crop, N, P, K)
        market_preview = get_market_forecast(best_crop)
        st.markdown(f"**{T('listen_btn')}**")
        render_tts_player(
            build_tts_summary(best_label, fert_preview, market_preview,
                              lang=st.session_state.get("lang","en"),
                              crop_key=best_crop),
            lang=st.session_state.get("lang","en"))

    st.divider()

    # ── Runner-ups ────────────────────────────────────────────────────────────
    st.markdown(f"### 🌱 {T('top_n_recs')}")
    rec_cols = st.columns(min(top_n, 4))
    for i, col in enumerate(rec_cols[:top_n]):
        with col:
            nm   = get_display_name(top_n_crops[i])
            ci   = get_crop_info(top_n_crops[i])
            rank = ["🥇","🥈","🥉","4️⃣","5️⃣","6️⃣","7️⃣"][i]
            pct_i = int(top_n_probs[i]*100)
            st.markdown(f"""
            <div style="background:{'rgba(37,99,235,.06)' if i==0 else 'rgba(0,0,0,.02)'};
                 border:1px solid {'rgba(37,99,235,.2)' if i==0 else 'rgba(0,0,0,.07)'};
                 border-radius:14px;padding:1rem;text-align:center;height:100%;">
              <div style="font-size:1.4rem;">{rank}</div>
              <div style="font-weight:600;font-size:.9rem;margin:.4rem 0;">{nm}</div>
              <div style="font-size:1.3rem;font-weight:700;color:{'#1e3a8a' if i==0 else '#444'};">{pct_i}%</div>
              <div style="font-size:.75rem;color:#888;margin-top:4px;">{ci['icon']} {ci['season']}</div>
              <div style="background:#eff6ff;border-radius:6px;height:6px;margin-top:8px;overflow:hidden;">
                <div style="background:#2563eb;height:6px;width:{pct_i}%;border-radius:6px;"></div>
              </div>
            </div>""", unsafe_allow_html=True)
    st.divider()

    # ── Environmental dashboard ───────────────────────────────────────────────
    if show_dashboard:
        st.markdown(f'<h3 style="color: #0f172a;">{T("env_analysis")}</h3>', unsafe_allow_html=True)
        d1, d2, d3, d4 = st.columns(4)

        def gauge(val, title, rng, color, steps):
            fig = go.Figure(go.Indicator(mode="gauge+number", value=val,
                title={"text":title,"font":{"size":13,"color":"#444"}},
                number={"font":{"size":26,"color":"#0f172a"}},
                gauge={"axis":{"range":rng,"tickcolor":"#888","tickfont":{"color":"#888"}},
                       "bar":{"color":color,"thickness":.25},
                       "bgcolor":"rgba(0,0,0,0)","borderwidth":0,
                       "steps":steps}))
            fig.update_layout(height=200, margin=dict(l=15,r=15,t=40,b=5),
                              paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
            return fig

        with d1: st.plotly_chart(gauge(temp,"Temperature °C",[0,50],"#e05252",
            [{"range":[0,20],"color":"#dbeafe"},{"range":[20,35],"color":"#dcfce7"},{"range":[35,50],"color":"#fee2e2"}]),
            use_container_width=True)
        with d2: st.plotly_chart(gauge(humidity,"Humidity %",[0,100],"#4a90d9",
            [{"range":[0,40],"color":"#f1f5f9"},{"range":[40,70],"color":"#dcfce7"},{"range":[70,100],"color":"#dbeafe"}]),
            use_container_width=True)
        with d3:
            pc = "#2563eb" if 5.5<=ph<=7.5 else "#e76f51"
            st.plotly_chart(gauge(ph,"Soil pH",[3,9],pc,
                [{"range":[3,5.5],"color":"#fee2e2"},{"range":[5.5,7.5],"color":"#dcfce7"},{"range":[7.5,9],"color":"#fef9c3"}]),
                use_container_width=True)
        with d4: st.plotly_chart(gauge(rainfall,"Rainfall mm",[0,500],"#4895ef",
            [{"range":[0,100],"color":"#fef9c3"},{"range":[100,250],"color":"#dcfce7"},{"range":[250,500],"color":"#dbeafe"}]),
            use_container_width=True)

        rc, bc = st.columns(2)
        with rc:
            fig = go.Figure(go.Scatterpolar(
                r=[N,P,K,N], theta=[T("nitrogen"), T("phosphorus"), T("potassium"), T("nitrogen")],
                fill="toself", line_color="#2563eb", fillcolor="rgba(37,99,235,.15)",
                mode="lines+markers", marker=dict(color="#2563eb",size=8)))
            fig.update_layout(
                polar=dict(
                    radialaxis=dict(visible=True, range=[0,max(150,N,P,K)+10], tickfont=dict(size=10, color="black")),
                    angularaxis=dict(tickfont=dict(size=11, color="black"))
                ),
                showlegend=False, title={"text":T("npk_title"),"x":.5,"font":{"size":14,"color":"black"}},
                height=300, margin=dict(l=30,r=30,t=50,b=20),
                paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig, use_container_width=True)
            st.markdown(f'<div style="font-size:0.85rem; color:#444; padding:0 10px;">{T("npk_desc")}</div>', unsafe_allow_html=True)
        with bc:
            clabels = [get_display_name(c) for c in top_n_crops]
            cpcts   = [p*100 for p in top_n_probs]
            colors  = ["#1e3a8a" if i==0 else "#60a5fa" for i in range(len(clabels))]
            fig = go.Figure(go.Bar(x=cpcts, y=clabels, orientation="h",
                marker=dict(color=colors, cornerradius=6),
                text=[f"{c:.1f}%" for c in cpcts], textposition="outside",
                textfont=dict(size=12)))
            fig.update_layout(title={"text":"AI Confidence Scores","x":.5,"font":{"size":14}},
                xaxis=dict(range=[0,108],title="",showgrid=False,showticklabels=False),
                yaxis=dict(autorange="reversed"),height=300,
                margin=dict(l=10,r=50,t=50,b=20),
                paper_bgcolor="rgba(0,0,0,0)",plot_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig, use_container_width=True)
        st.divider()

    # ── Fertilizer prescription ───────────────────────────────────────────────
    st.markdown(f"### {T('fert_title')}")
    st.markdown(T("fert_desc"))
    fert = calculate_fertilizer_prescription(best_crop, N, P, K)

    if fert["all_optimal"]:
        st.success(T("fert_optimal"))
    else:
        req = fert["required"]
        f1, f2, f3 = st.columns(3)
        with f1:
            d = fert["deficit_N"]
            st.metric(T("nitrogen"), f"{N} kg/ha",
                      f"Need {req['N']} — Deficit: {d}",
                      delta_color="normal" if d==0 else "inverse")
        with f2:
            d = fert["deficit_P"]
            st.metric(T("phosphorus"), f"{P} kg/ha",
                      f"Need {req['P']} — Deficit: {d}",
                      delta_color="normal" if d==0 else "inverse")
        with f3:
            d = fert["deficit_K"]
            st.metric(T("potassium"), f"{K} kg/ha",
                      f"Need {req['K']} — Deficit: {d}",
                      delta_color="normal" if d==0 else "inverse")

        st.markdown('<div class="fert-card">', unsafe_allow_html=True)
        st.markdown(f"**{T('presc_header')}**")
        pc1, pc2, pc3 = st.columns(3)

        # ── FIX: expanded if/else blocks — no inline ternary inside with ────
        with pc1:
            if fert["urea_kg"] > 0:
                st.metric(T("urea_label"), f"{fert['urea_kg']} kg", T("kg_per_ha"))
            else:
                st.metric(T("urea_label"), T("no_deficit"))

        with pc2:
            if fert["dap_kg"] > 0:
                st.metric(T("dap_label"), f"{fert['dap_kg']} kg", T("kg_per_ha"))
            else:
                st.metric(T("dap_label"), T("no_deficit"))

        with pc3:
            if fert["mop_kg"] > 0:
                st.metric(T("mop_label"), f"{fert['mop_kg']} kg", T("kg_per_ha"))
            else:
                st.metric(T("mop_label"), T("no_deficit"))

        st.markdown('</div>', unsafe_allow_html=True)
    st.divider()

    # ── Market forecast ───────────────────────────────────────────────────────
    st.markdown(f"### {T('market_title')}")
    market = get_market_forecast(best_crop)

    mc1, mc2, mc3, mc4, mc5 = st.columns(5)
    mc1.metric(T("market_price"),   f"Rs.{market['price_per_q']:,}", "/quintal")
    mc2.metric(T("market_yield"),   f"{market['yield_q_ha']} q",    T("per_ha"))
    mc3.metric(T("market_revenue"), f"Rs.{market['revenue']:,}",    T("per_ha"))
    mc4.metric(T("market_cost"),    f"Rs.{market['input_cost']:,}", T("per_ha"))
    mc5.metric(T("market_profit"),  f"Rs.{market['net_profit']:,}",
               f"ROI {market['roi_pct']}%",
               delta_color="normal" if market["net_profit"]>0 else "inverse")

    st.markdown('<div class="market-card">', unsafe_allow_html=True)
    fig = go.Figure(go.Waterfall(
        orientation="v", measure=["relative","relative","total"],
        x=["Revenue","Input Cost","Net Profit"],
        y=[market["revenue"], -market["input_cost"], 0],
        connector={"line":{"color":"rgba(0,0,0,.15)","width":1}},
        increasing={"marker":{"color":"#2563eb","line":{"color":"#1e3a8a","width":1}}},
        decreasing={"marker":{"color":"#e05252","line":{"color":"#c0392b","width":1}}},
        totals={"marker":{"color":"#2463ae","line":{"color":"#1a4f8a","width":1}}},
        text=[f"Rs.{market['revenue']:,}", f"-Rs.{market['input_cost']:,}", f"Rs.{market['net_profit']:,}"],
        textposition="outside", textfont=dict(size=12)))
    fig.update_layout(
        title={"text":f"Per Hectare Economics — {best_label}","x":.5,"font":{"size":14}},
        yaxis=dict(title="INR (Rs.)", showgrid=True, gridcolor="rgba(0,0,0,.06)"),
        height=320, margin=dict(l=20,r=20,t=55,b=20),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
    st.plotly_chart(fig, use_container_width=True)
    st.caption(f"ℹ️ {T('market_note')}")
    st.markdown('</div>', unsafe_allow_html=True)
    st.divider()

    # ── History ───────────────────────────────────────────────────────────────
    if show_history:
        st.markdown(f"### {T('history_title')}")
        if "history" not in st.session_state: st.session_state.history = []
        st.session_state.history.append({
            T("district_lbl"):district, "Temp":temp, "Humidity":humidity,
            "pH":ph, "Rainfall":rainfall, "Top Pick":best_label,
            "Confidence":f"{best_conf:.1f}%"})
        st.dataframe(pd.DataFrame(st.session_state.history),
                     use_container_width=True, hide_index=True)
        if st.button(T("clear_history")):
            st.session_state.history = []; st.rerun()

    # ── PDF export ────────────────────────────────────────────────────────────
    st.markdown(f"### {T('export_title')}")
    st.markdown(T("export_desc"))
    pdf_bytes = create_pdf_report(
        district, best_label, best_conf, temp, humidity, ph,
        rainfall, N, P, K, fert, market,
        lang=st.session_state.get("lang","en"))
    st.download_button(label=T("download_pdf"), data=pdf_bytes,
        file_name=f"{district}_Crop_Report_{datetime.date.today()}.pdf",
        mime="application/pdf", use_container_width=True)
    st.divider()

    # ── Input summary ─────────────────────────────────────────────────────────
    with st.expander(T("input_summary")):
        summary = {
            T("district_lbl"):district, T("temperature"):temp,
            T("humidity"):humidity, T("nitrogen"):N,
            T("phosphorus"):P, T("potassium"):K,
            T("soil_ph"):ph, T("rainfall_mm"):rainfall}
        st.table(pd.DataFrame.from_dict(summary, orient="index", columns=[T("value")]))